package com.store.products.db

import com.store.products.ProductDetails
import com.store.products.ProductType
import kotlinx.coroutines.CoroutineName
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.async
import kotlinx.coroutines.awaitAll
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.launch
import kotlinx.coroutines.test.runTest
import kotlinx.coroutines.withContext
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

class ProductDbTest {
    @Test
    fun `saved product id and generated id should be same`() =
        runTest {
            val db: ProductRepo = InMemoryProductDb()
            coroutineScope {
                val jobs =
                    (1..100).map { i ->
                        async {
                            var savedId = db.save(ProductDetails(null, "Product $i", ProductType.gadget, i * 25, i * 25.0))
                            assertEquals(i, savedId, "Generated id and the saved id should be same")
                        }
                    }
                jobs.awaitAll()
            }
            assertEquals(100, db.findAll(null).size, "All products size should be 100")
        }

    @Test
    fun `save 2 products async and still generated id is correct`() =
        runTest {
            val db: ProductRepo = InMemoryProductDb()
            coroutineScope {
                val initialSize =
                    async {
                        db.findAll(null).size
                    }
                coroutineScope {
                    launch { db.save(ProductDetails(null, "Product 1", ProductType.gadget, 25, 25.0)) }
                    launch { db.save(ProductDetails(null, "Product 2", ProductType.gadget, 25, 25.0)) }
                    assertEquals(0, initialSize.await(), "initial size should be 0")
                }

                assertEquals(2, db.findAll(null).size, "All products size should be 2")
                assertEquals(2, db.findAll(ProductType.gadget).size, "Gadget products size should be 2")
            }
        }

    @Test
    fun `concurrent saves should generate unique Ids and maintain data integrity`() =
        runTest {
            val db: ProductRepo = InMemoryProductDb()
            val productCount = 1000
            val types = ProductType.entries

            val jobs =
                List(productCount) { i ->
                    async {
                        val type = types.random()
                        db.save(ProductDetails(-1, "Product $i", type, i * 25, i * 25.0))
                    }
                }

            val generatedIds = jobs.awaitAll()

            assertEquals(productCount, db.findAll(null).size, "All products should be saved")
            assertEquals(generatedIds.toSet().size, productCount, "All products should have unique ids")

            assertTrue(generatedIds.all { it in 1..productCount }, "Ids should be in range 1 to $productCount")
        }

    @Test
    fun `concurrent reads and writes`() =
        runTest {
            val db = InMemoryProductDb()

            val writeCount = 1000
            val readCount = 20
            val writeJobs =
                List(writeCount) {
                    async {
                        db.save(ProductDetails(-1, "Product $it", ProductType.book, it * 25, it * 25.0))
                    }
                }

            val readJobs =
                List(readCount) {
                    async {
                        val products = db.findAll(null)
                        assertTrue(products.all { it.id!! > 0 }, "All products should have id greater than 0, i.e generated by server")
                        products.size
                    }
                }

            writeJobs.awaitAll()
            val readProducts = readJobs.awaitAll()
            assertEquals(writeCount, db.findAll(null).size, "All writes should be successful")
            assertTrue(readProducts.all { it <= writeCount }, "Read operations should never see more products then written")
        }

    @Test
    fun `filtering by type should be thread-safe`() =
        runTest {
            val db = InMemoryProductDb()

            val productsPerType = 100
            val saveJobs =
                ProductType.entries.flatMap { type ->
                    List(productsPerType) {
                        async { db.save(ProductDetails(null, "Product $type $it", type, it * 25, it * 25.0)) }
                    }
                }

            val readJobs =
                ProductType.entries.map { type ->
                    async {
                        repeat(10) {
                            val products = db.findAll(type)
                            assertTrue(products.all { it.type == type }, "All products should have same type")
                        }
                    }
                }

            saveJobs.awaitAll()
            readJobs.awaitAll()

            ProductType.entries.forEach { type ->
                assertEquals(productsPerType, db.findAll(type).size, "Each type should have $productsPerType products")
            }
        }

    @Test
    fun `multiple concurrent writers`() =
        runTest {
            val db = InMemoryProductDb()

            val concurrentWriters = 50
            val iterationsPerWriter = 20
            withContext(Dispatchers.Default + CoroutineName("concurrent-writers")) {
                val jobs =
                    List(concurrentWriters) { writerId ->
                        async {
                            repeat(iterationsPerWriter) { iteration ->
                                val type = ProductType.entries[iteration % ProductType.entries.size]
                                db.save(
                                    ProductDetails(null, "Product $writerId Iteration $iteration", type, iteration * 25, iteration * 25.0),
                                )
                            }
                        }
                    }
                jobs.awaitAll()
            }

            val expectedTotalProducts = concurrentWriters * iterationsPerWriter
            val totalSavedProducts = db.findAll(null).size
            assertEquals(expectedTotalProducts, totalSavedProducts, "All products should be saved")
        }
}
